compile: raceCondition.c raceCondition-seq.c
	gcc -o raceCondition raceCondition.c -lm -lpthread
	gcc -o raceCondition-seq raceCondition-seq.c -lm -lpthread

clean:
	rm raceCondition raceCondition-seq