compile: ex6.c ex8-sir.c ex7.c ex9-sir
	gcc -o ex6 ex6.c -lm -O3 -lpthread
	gcc -o ex8-sir ex8-sir.c -lm -O3 -lpthread
	gcc -o ex9-sir ex9-sir.c -lm -O3 -lpthread
	gcc -o ex7 ex7.c -lm -O3 -lpthread



clean:
	rm ex6 ex8-sir ex7 ex9-sir